# Generated by Django 2.2 on 2019-11-05 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('GoodsName', models.TextField(blank=True, null=True)),
                ('GoodsPrice', models.DecimalField(blank=True, decimal_places=10, max_digits=2, null=True)),
            ],
            options={
                'db_table': 'Goods',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('OrderDate', models.DateField(blank=True, null=True)),
                ('Goods', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_market.Goods')),
            ],
            options={
                'db_table': 'Orders',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.TextField(blank=True)),
                ('LastName', models.TextField(blank=True)),
                ('BirthDate', models.DateField(blank=True, null=True)),
                ('RegistrationDate', models.DateField(blank=True)),
                ('Order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_market.Orders')),
            ],
            options={
                'db_table': 'User',
                'managed': True,
            },
        ),
    ]
